name: Run Algo Every 15 Minutes

on:
  schedule:
    - cron: "*/15 * * * *"  # Every 15 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
        echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> .env
        echo "REDIRECT_URI=${{ secrets.REDIRECT_URI }}" >> .env
        echo "API_KEY=${{ secrets.API_KEY }}" >> .env
        echo "FEED_TOKEN=${{ secrets.FEED_TOKEN }}" >> .env
        echo "CLIENT_CODE=${{ secrets.CLIENT_CODE }}" >> .env
        echo "TOTP_SECRET=${{ secrets.TOTP_SECRET }}" >> .env
        echo "GMAIL_ID=${{ secrets.GMAIL_ID }}" >> .env
        echo "GMAIL_PASSWORD=${{ secrets.GMAIL_PASSWORD }}" >> .env
        echo "SHEET_ID=${{ secrets.SHEET_ID }}" >> .env
        echo "GDRIVE_JSON_PATH=credentials.json" >> .env

    - name: Decode and Save Google Credentials
      run: |
        echo "${{ secrets.GDRIVE_JSON_BASE64 }}" | base64 -d > credentials.json

    - name: Run Python Script
      run: python main.py

